# -*- coding: utf-8 -*-
"""02_train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOmYSy1UqiXgAdtBc6L7IQ215aBMTmSg

# 2. Train one model

Generalizable script to allow us to run a training loop for a single model per session. Requires 01_prepare_data.ipynb to have been run in order to produce the train/val data split.
"""

from google.colab import drive
drive.mount('/content/drive')

import sys, os
DRIVE_ROOT = "/content/drive/MyDrive/comparison/boilerplate/"
sys.path.append(DRIVE_ROOT)

import fer_common as fc
paths = fc.get_paths(DRIVE_ROOT)

!ls -la /content/drive/MyDrive/comparison/boilerplate/data/

import json
import torch
from torch.utils.data import DataLoader
from torchvision import datasets

# Sanity check
class_names = fc.load_class_names(paths)
class_weights = fc.load_class_weights(paths)
print("Classes:", class_names)

# Copy train/val split data into memory
import shutil

LOCAL_TRAIN_DIR = "/content/data/train"
LOCAL_VAL_DIR = "/content/data/val"

if not os.path.exists(LOCAL_TRAIN_DIR):
    print("Copying train/val from Drive to memory")
    shutil.copytree(paths["train_dir"], LOCAL_TRAIN_DIR)
    shutil.copytree(paths["val_dir"], LOCAL_VAL_DIR)
    print("Done.")
else:
    print("Local data already present.")

# Change on each run:  inception_v3, densenet121, shufflenet_v2_x2_0, resnet18,
# regnet_y_400mf, mobilenet_v3_small, googlenet, efficientnet_v2_s , alexnet
MODEL_NAME = "inception_v3"  # <-- one of:

BATCH_SIZE = 64
EPOCHS = 30
LEARNING_RATE = 1e-4

config = fc.get_model_config(MODEL_NAME)
print(f"Training {config['name']} at input size {config['input_size']}")

# Load training data from memory.
train_tf = fc.build_transforms(config["input_size"], train=True)
val_tf = fc.build_transforms(config["input_size"], train=False)

train_dataset = datasets.ImageFolder(LOCAL_TRAIN_DIR, transform=train_tf)
val_dataset = datasets.ImageFolder(LOCAL_VAL_DIR, transform=val_tf)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,
                           num_workers=4, pin_memory=True, persistent_workers=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False,
                         num_workers=4, pin_memory=True, persistent_workers=True)

print(f"Train: {len(train_dataset)}  Val: {len(val_dataset)}")

### Training the model

model_weights_dir = os.path.join(paths["weights_dir"], MODEL_NAME)
os.makedirs(model_weights_dir, exist_ok=True)

# Save best performing model weights across all epochs
ckpt_path = os.path.join(model_weights_dir, "best_model.pth")

net = fc.BackboneClassifier(config["fn"], num_classes=len(class_names), lr=LEARNING_RATE, epochs=EPOCHS)
history = net.train_(
    train_loader,
    epochs=EPOCHS,
    class_weights=class_weights,
    val_loader=val_loader,
    ckpt_path=ckpt_path,
)

# Save train/val loss history for visualization
history_path = os.path.join(model_weights_dir, "history.json")
with open(history_path, "w") as f:
    json.dump(history, f)

print(f"Saved weights to {ckpt_path}")
print(f"Saved history to {history_path}")