# -*- coding: utf-8 -*-
"""03_evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OnxPBn33APfRuvriTzpHAGoHNlj-XlpO

# 3. Evaluate all trained models

Loads pre-saved model weights and runs every existent model against FER2013 test
set. Produces visualizations to represent model performance.
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import sys, os
DRIVE_ROOT = "/content/drive/MyDrive/comparison/boilerplate/"
sys.path.append(DRIVE_ROOT)

import fer_common as fc
paths = fc.get_paths(DRIVE_ROOT)

import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
from torch.utils.data import DataLoader
from torchvision import datasets
from sklearn.metrics import (
    confusion_matrix, classification_report,
    f1_score, precision_score, recall_score,
)

BATCH_SIZE = 64
class_names = fc.load_class_names(paths)

# Copy data over from drive to memory.
import shutil

LOCAL_TEST_DIR = "/content/data/test"

if not os.path.exists(LOCAL_TEST_DIR):
    print("Copying test set from Drive to local disk...")
    shutil.copytree(paths["test_dir"], LOCAL_TEST_DIR)
    print("Done.")
else:
    print("Local data already present, skipping copy.")

available = []
for cfg in fc.MODEL_CONFIGS:
    ckpt_path = os.path.join(paths["weights_dir"], cfg["name"], "best_model.pth")
    if os.path.exists(ckpt_path):
        available.append(cfg)
    else:
        print(f"Skipping {cfg['name']} — no checkpoint found yet")

print("\nWill evaluate:", [c["name"] for c in available])

def load_trained_model(cfg, num_classes):
    ckpt_path = os.path.join(paths["weights_dir"], cfg["name"], "best_model.pth")
    net = fc.BackboneClassifier(cfg["fn"], num_classes=num_classes, pretrained=False)
    net.load_state_dict(torch.load(ckpt_path, map_location=net.device))
    net.eval()
    return net


def make_test_loader(input_size, batch_size=BATCH_SIZE):
    test_tf = fc.build_transforms(input_size, train=False)
    test_dataset = datasets.ImageFolder(LOCAL_TEST_DIR, transform=test_tf)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True,
                              num_workers=4, pin_memory=True)
    return test_loader, test_dataset.classes


def evaluate_and_plot(cfg):
    name = cfg["name"]

    try:
        net = load_trained_model(cfg, num_classes=len(class_names))
        test_loader, test_class_names = make_test_loader(cfg["input_size"])

        accuracy, all_predicted, all_targets, all_outputs = net.test_(test_loader)

        f1 = f1_score(all_targets, all_predicted, average="weighted")
        precision = precision_score(all_targets, all_predicted, average="weighted")
        recall = recall_score(all_targets, all_predicted, average="weighted")

        print("=" * 40)
        print(f"  Model         : {name}")
        print(f"  Test Accuracy : {accuracy:.4f}")
        print(f"  F1 Score      : {f1:.4f}")
        print(f"  Precision     : {precision:.4f}")
        print(f"  Recall        : {recall:.4f}")
        print("=" * 40)

        cm = confusion_matrix(
            all_targets,
            all_predicted,
            labels=range(len(test_class_names))
        )

        # Avoid division-by-zero for classes with no test samples
        row_sums = cm.sum(axis=1, keepdims=True)
        cm_norm = np.divide(
            cm.astype(float),
            row_sums,
            out=np.zeros_like(cm, dtype=float),
            where=row_sums != 0
        )

        # Raw confusion matrix
        plt.figure(figsize=(10, 8))
        sns.heatmap(
            cm,
            annot=True,
            fmt="d",
            cmap="Blues",
            xticklabels=test_class_names,
            yticklabels=test_class_names
        )
        plt.xlabel("Predicted Label")
        plt.ylabel("True Label")
        plt.title(f"Confusion Matrix (Raw Counts) — {name}")
        plt.tight_layout()
        plt.show()
        plt.close()

        # Normalized confusion matrix
        plt.figure(figsize=(10, 8))
        sns.heatmap(
            cm_norm,
            annot=True,
            fmt=".2f",
            cmap="Blues",
            xticklabels=test_class_names,
            yticklabels=test_class_names,
            vmin=0,
            vmax=1
        )
        plt.xlabel("Predicted Label")
        plt.ylabel("True Label")
        plt.title(f"Confusion Matrix (Row Normalised) — {name}")
        plt.tight_layout()
        plt.show()
        plt.close()

        # Classification report
        report_dict = classification_report(
            all_targets,
            all_predicted,
            target_names=test_class_names,
            output_dict=True,
            zero_division=0
        )

        report_df = pd.DataFrame(report_dict).transpose()
        report_df = report_df.drop(columns=["support"])
        report_df = report_df.loc[test_class_names]

        plt.figure(figsize=(10, 6))
        sns.heatmap(
            report_df,
            annot=True,
            cmap="viridis",
            fmt=".2f",
            vmin=0,
            vmax=1
        )
        plt.title(f"Classification Report Heatmap — {name}")
        plt.ylabel("Class")
        plt.xlabel("Metrics")
        plt.tight_layout()
        plt.show()
        plt.close()

        return {
            "name": name,
            "accuracy": accuracy,
            "f1": f1,
            "precision": precision,
            "recall": recall
        }

    except Exception as e:
        print("\n" + "!" * 60)
        print(f"ERROR evaluating model: {name}")
        print(f"Error type: {type(e).__name__}")
        print(f"Error: {e}")
        print("Skipping this model and moving to the next one...")
        print("!" * 60 + "\n")

        return None

results = [evaluate_and_plot(cfg) for cfg in available]
results_df = pd.DataFrame(results).sort_values("accuracy", ascending=False)
results_df

histories = {}
for cfg in available:
    hist_path = os.path.join(paths["weights_dir"], cfg["name"], "history.json")
    if os.path.exists(hist_path):
        with open(hist_path) as f:
            histories[cfg["name"]] = json.load(f)

if histories:
    fig, axes = plt.subplots(1, 3, figsize=(20, 5))
    for name, hist in histories.items():
        epochs_ran = range(1, len(hist["train_loss"]) + 1)
        axes[0].plot(epochs_ran, hist["train_loss"], label=name)
        if hist["val_loss"]:
            axes[1].plot(epochs_ran, hist["val_loss"], label=name)
            axes[2].plot(epochs_ran, hist["val_acc"], label=name)
    axes[0].set_title("Train Loss")
    axes[1].set_title("Val Loss")
    axes[2].set_title("Val Accuracy")
    for ax in axes:
        ax.set_xlabel("Epoch")
        ax.legend(fontsize=8)
    plt.tight_layout()
    plt.show()
else:
    print("No history.json files found — nothing to plot.")

### Sanity Check

import os

def verify_split(train_dir, val_dir, expected_ratio=0.8, tolerance=0.02):
    classes = sorted(os.listdir(train_dir))
    total_train, total_val = 0, 0
    any_overlap = False

    print(f"{'Class':<12} {'Train':>7} {'Val':>7} {'Train %':>9}")
    print("-" * 42)

    for cls in classes:
        train_files = set(os.listdir(os.path.join(train_dir, cls)))
        val_files = set(os.listdir(os.path.join(val_dir, cls)))

        n_train, n_val = len(train_files), len(val_files)
        total_train += n_train
        total_val += n_val
        pct = n_train / (n_train + n_val)

        flag = "  ⚠️ off ratio" if abs(pct - expected_ratio) > tolerance else ""
        print(f"{cls:<12} {n_train:>7} {n_val:>7} {pct:>8.1%}{flag}")

        overlap = train_files & val_files
        if overlap:
            any_overlap = True
            print(f"  ⚠️  {len(overlap)} overlapping filenames in '{cls}': {list(overlap)[:5]}")

    overall_pct = total_train / (total_train + total_val)
    print("-" * 42)
    print(f"{'TOTAL':<12} {total_train:>7} {total_val:>7} {overall_pct:>8.1%}")
    print()
    print("✅ Split ratio OK" if abs(overall_pct - expected_ratio) <= tolerance else "⚠️ Split ratio off")
    print("✅ No overlapping filenames" if not any_overlap else "⚠️ Overlap found — see above")


verify_split(paths["train_dir"], paths["val_dir"])

