# -*- coding: utf-8 -*-
"""FER2013 Facial Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AyqdEemmkbOYwwsSTov62uAo_YQywG15
"""



import os
import torch
import torch.nn as nn
import torchvision.models as models

import numpy as np
import torch.nn.functional as F
import torch.optim as optim
import torchvision.transforms as transforms
from torchvision import datasets
from torch.utils.data import DataLoader, SubsetRandomSampler
from sklearn.model_selection import StratifiedShuffleSplit

import kagglehub

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np


class FER2013CNN(nn.Module):
    def __init__(self, num_classes=7, lr=1e-4, epochs=30):
        super(FER2013CNN, self).__init__()

        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        class ResidualBlock(nn.Module):
            def __init__(self, channels):
                super().__init__()
                self.conv1 = nn.Conv2d(channels, channels, 3, padding=1)
                self.bn1 = nn.BatchNorm2d(channels)
                self.conv2 = nn.Conv2d(channels, channels, 3, padding=1)
                self.bn2 = nn.BatchNorm2d(channels)
                self.relu = nn.ReLU()

            def forward(self, x):
                identity = x
                out = self.relu(self.bn1(self.conv1(x)))
                out = self.bn2(self.conv2(out))
                return self.relu(identity + out)

        self.features = nn.Sequential(
            nn.Conv2d(1, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            ResidualBlock(64),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            ResidualBlock(128),
            nn.MaxPool2d(2),

            nn.Conv2d(128, 256, 3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            ResidualBlock(256),
            ResidualBlock(256),

            nn.AdaptiveAvgPool2d((1, 1))
        )

        self.classifier = nn.Sequential(
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(128, num_classes)
        )

        self.optimizer = optim.AdamW(self.parameters(), lr=lr, weight_decay=1e-4)

        self.scheduler = optim.lr_scheduler.CosineAnnealingLR(
            self.optimizer,
            T_max=epochs
        )

        self.to(self.device)

    def forward(self, x):
        x = x.to(self.device)
        x = self.features(x)
        x = torch.flatten(x, 1)
        x = self.classifier(x)
        return x

    def _loss_(self, outputs, targets, class_weights=None):
        targets = targets.to(self.device)

        if class_weights is not None:
            class_weights = class_weights.to(self.device)
            loss_fn = nn.CrossEntropyLoss(weight=class_weights, label_smoothing=0.1)
        else:
            loss_fn = nn.CrossEntropyLoss(label_smoothing=0.1)

        return loss_fn(outputs, targets)

    def train_(self, train_loader, epochs=30, class_weights=None, val_loader=None):
        best_val_acc = 0
        for epoch in range(epochs):
            self.train()
            total_train_loss = 0

            for x, targets in train_loader:
                x, targets = x.to(self.device), targets.to(self.device)

                self.optimizer.zero_grad()
                outputs = self.forward(x)
                loss = self._loss_(outputs, targets, class_weights)

                loss.backward()
                torch.nn.utils.clip_grad_norm_(self.parameters(), 5.0)
                self.optimizer.step()

                total_train_loss += loss.item()

            avg_train_loss = total_train_loss / len(train_loader)

            if val_loader is not None:
                self.eval()
                total_val_loss = 0
                correct = 0
                total = 0

                with torch.no_grad():
                    for x_val, targets_val in val_loader:
                        x_val, targets_val = x_val.to(self.device), targets_val.to(self.device)
                        outputs_val = self.forward(x_val)

                        val_loss = self._loss_(outputs_val, targets_val, class_weights)
                        total_val_loss += val_loss.item()

                        _, predicted = torch.max(outputs_val, 1)
                        total += targets_val.size(0)
                        correct += (predicted == targets_val).sum().item()

                avg_val_loss = total_val_loss / len(val_loader)
                val_acc = correct / total

                if val_acc > best_val_acc:
                    best_val_acc = val_acc
                    torch.save(self.state_dict(), "best_model.pth")

                print(f"Epoch [{epoch+1}/{epochs}] Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f} | Val Acc: {val_acc:.4f}")
                self.scheduler.step()
            else:
                print(f"Epoch [{epoch+1}/{epochs}] Train Loss: {avg_train_loss:.4f}")
        self.load_state_dict(torch.load("best_model.pth"))

    def test_(self, data_loader):
        self.eval()
        correct = 0
        total = 0

        all_preds, all_targets, all_logits = [], [], []

        with torch.no_grad():
            for x, targets in data_loader:
                x, targets = x.to(self.device), targets.to(self.device)
                outputs = self.forward(x)

                _, predicted = torch.max(outputs, 1)

                total += targets.size(0)
                correct += (predicted == targets).sum().item()

                all_preds.extend(predicted.cpu().numpy())
                all_targets.extend(targets.cpu().numpy())
                all_logits.extend(outputs.cpu().numpy())

        return correct / total, np.array(all_preds), np.array(all_targets), np.array(all_logits)

path = kagglehub.dataset_download("msambare/fer2013")

print("Path to dataset files:", path)

import shutil
import os

target_dir = "/content/fer2013"
os.makedirs(target_dir, exist_ok=True)

# Copy dataset over to content cache
for item_name in os.listdir(path):
  source_path = os.path.join(path, item_name)
  destination_path = os.path.join(target_dir, item_name)
  if os.path.isdir(source_path):
    shutil.copytree(source_path, destination_path)
  else:
    shutil.copy(source_path, destination_path)

train_transform = transforms.Compose([
    transforms.Grayscale(num_output_channels=1),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(20),
    transforms.RandomAffine(degrees=0, translate=(0.1,0.1), scale=(0.9,1.1)),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

val_transform = transforms.Compose([
    transforms.Grayscale(num_output_channels=1),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

path = os.getcwd()

dataset_for_split = datasets.ImageFolder(os.path.join(path, 'fer2013/train'))
targets = np.array(dataset_for_split.targets)

num_classes = len(dataset_for_split.classes)
print('Dataset classes:', dataset_for_split.classes)

# Perform 80/20 train-validation split
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, val_idx = next(sss.split(np.zeros(len(targets)), targets))

train_dataset = datasets.ImageFolder(os.path.join(path, 'fer2013/train'), transform=train_transform)
val_dataset = datasets.ImageFolder(os.path.join(path, 'fer2013/train'), transform=val_transform)
train_loader = DataLoader(train_dataset, batch_size=64, sampler=SubsetRandomSampler(train_idx))
val_loader = DataLoader(val_dataset, batch_size=64, sampler=SubsetRandomSampler(val_idx))

from collections import Counter
train_targets = targets[train_idx]
class_counts = Counter(train_targets)
total_samples = sum(class_counts.values())
weights = torch.zeros(num_classes, dtype=torch.float32)

for i in range(num_classes):
    if class_counts[i] > 0:
        weights[i] = total_samples / (num_classes * class_counts[i])
    else:
        weights[i] = 0.0

class_weights = weights

print("Class counts (training set):", class_counts)
print("Weights per class (training set):", class_weights)

"""Training and validation dataloaders have been created with an 80/20 train-validation split."""

for x in range(len(class_weights)):
    print(f"{dataset_for_split.classes[x]} weight:\t{class_weights[x]:.4f}")

os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
model = FER2013CNN(num_classes=num_classes, lr=0.0001)

print('Training CNN model...')
model.train_(train_loader, epochs=40, class_weights=class_weights, val_loader=val_loader)

torch.save(model.state_dict(), "model_weights.pth")

path = os.getcwd()
test_dataset = datasets.ImageFolder(os.path.join(path, 'fer2013/test'), transform=val_transform)

num_test_classes = len(test_dataset.classes)
print('Test Dataset classes:', test_dataset.classes)

test_loader = DataLoader(test_dataset, batch_size=64, shuffle=True)

from sklearn.metrics import confusion_matrix, roc_curve, auc, accuracy_score, classification_report
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Evaluate the model
accuracy, all_predicted, all_targets, all_outputs = model.test_(test_loader)
print(f'Test Accuracy: {accuracy:.4f}')
class_names = test_dataset.classes

# Confusion Matrix
cm = confusion_matrix(all_targets, all_predicted)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

# Classification report
report_dict = classification_report(all_targets, all_predicted, target_names=class_names, output_dict=True)
print("\nClassification Report:")
report_df = pd.DataFrame(report_dict).transpose()
report_df = report_df.drop(columns=['support'])
report_df = report_df.loc[class_names]
plt.figure(figsize=(10, 6))
sns.heatmap(report_df, annot=True, cmap='viridis', fmt='.2f')
plt.title('Classification Report Heatmap')
plt.ylabel('Class')
plt.xlabel('Metrics')
plt.show()